name: ldsc
channels:
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - python=2.7
  - cython
  - bitarray=0.8
  - nose=1.3
  - pybedtools=0.7
  - anaconda::scipy=0.19
  - conda-forge::pandas=0.20
  - anaconda::numpy=1.16